stages:
  - test
  - deploy

test_element:
  stage: test
  image: gitlab.wgtn.cat-it.co.nz:4567/rebeccastevens/docker-wct-image
  script:
    - yarn install
    - yarn run test
  only:
    - branches
  tags:
    - docker

lint:
  stage: test
  image: node:8.9.3
  script:
    - yarn install
    - yarn run lint
  only:
    - branches
  tags:
    - docker

update_bundle:
  stage: deploy
  script:
    - VERSION_REGEX='^v?([0-9]+\.)?([0-9]+\.)?([0-9]+)$'
    - if [[ $CI_COMMIT_TAG =~ $VERSION_REGEX ]]; then
    -   apt-get update && apt-get install -y curl
    -   curl -X POST -F token=$CATALYST_ELEMENTS_PIPELINE_TOKEN -F ref=$CATALYST_ELEMENTS_PIPELINE_REF https://gitlab.wgtn.cat-it.co.nz/api/v4/projects/1077/trigger/pipeline
    - else
    -   echo "Skipping - $CI_COMMIT_TAG is not a version tag."
    - fi
  only:
    - tags
