rules:
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 2
    - include: true
  property-sort-order:
    - 1
    - order: recess
  hex-length:
    - 1
    - style: long
  no-ids: 0
  no-color-literals: 0
  no-vendor-prefixes: 0
  no-duplicate-properties: 0
